import React, { createContext, useContext, ReactNode, useCallback } from 'react';
import { useLocalStorage } from 'usehooks-ts';

type Locale = 'en' | 'de';

interface Translations {
    [key: string]: string;
}

const translations: Record<Locale, Translations> = {
    en: {
        dashboard: 'Dashboard',
        streams: 'Streams',
        tasks: 'Tasks',
        profile: 'Profile',
        config: 'Configuration',
        refresh_stats: 'Refresh Stats',
        stats_refreshed: 'Stats refreshed successfully',
        failed_refresh: 'Failed to refresh stats',
        live: 'Live',
        viewers: 'Viewers',
        duration: 'Duration',
        bitrate: 'Bitrate',
        start_time: 'Start Time',
        arguments: 'Arguments',
        no_data: 'No data found',
        snapshot: 'Take Snapshot',
        reload: 'Reload Player',
        overview: 'Dashboard Overview',
        server_info: 'Server Information',
        active_streams: 'Active Streams',
        app: 'App',
        stream: 'Stream',
        stream_name: 'Stream Name',
        publisher_id: 'Publisher ID',
        publisher_state: 'Publisher State',
        broadcast_id: 'Broadcast ID',
        broadcast_state: 'Broadcast State',
        actions: 'Actions',
        delete: 'Delete',
        remove: 'Remove',
        add_task: 'Add Task',
        server_logs: 'Server Logs',
        logs_connected: 'Connected',
        logs_connecting: 'Connecting…',
        logs_disconnected: 'Disconnected',
        no_logs_yet: 'No log messages yet.',
        pause: 'Pause',
        resume: 'Resume',
        clear: 'Clear',
        confirm_delete: 'Are you sure you want to delete this?',
        confirm_remove_task: 'Remove this task?',
        yes: 'Yes',
        no: 'No',
        component_switch: 'Switch',
        component_relay: 'Relay',
        component_trans: 'Trans',
        component_fission: 'Fission',
        component_rtmp: 'RTMP',
        component_av: 'A/V',
        component_static: 'Static',
        background_tasks: 'Background Tasks',
        service_controls: 'Service Controls',
        running: 'RUNNING',
        stopped: 'STOPPED',
        restart: 'Restart',
        uptime: 'Uptime',
        url: 'URL',
        mode: 'Mode',
        path: 'Path',
        output_path: 'Output Path',
        status: 'Status',
        active_source: 'Active Source',
        pending: 'Pending',
        switch_to: 'Switch To',
        configured_sources: 'Configured Sources',
        active_streams_select: 'Active Streams',
        save_config: 'Save Configuration',
        config_updated: 'Configuration updated successfully',
        config_failed: 'Update failed',
        http_config: 'HTTP Configuration',
        https_config: 'HTTPS Configuration',
        rtmp_config: 'RTMP Configuration',
        auth_config: 'Authentication',
        logging_config: 'Logging',
        trans_config: 'Trans Configuration',
        relay_config: 'Relay Configuration',
        fission_config: 'Fission Configuration',
        switch_config: 'Switch Configuration',
        port: 'Port',
        enable_api: 'Enable API',
        web_root: 'Web Root',
        media_root: 'Media Root',
        allow_origin: 'Allow Origin',
        ssl_key_path: 'SSL Key Path',
        ssl_cert_path: 'SSL Cert Path',
        ssl_passphrase: 'SSL Passphrase',
        ssl_port: 'SSL Port',
        chunk_size: 'Chunk Size',
        ping_interval: 'Ping Interval',
        ping_timeout: 'Ping Timeout',
        gop_cache: 'Enable GOP Cache',
        api_auth: 'API Auth',
        api_user: 'API User',
        api_pass: 'API Password',
        play_auth: 'Play Auth',
        publish_auth: 'Publish Auth',
        secret_key: 'Secret Key',
        log_type: 'Log Type',
        log_length: 'Rolling Log Length',
        ffmpeg_path: 'FFmpeg Path',
        tasks_json: 'Tasks (JSON)',
        json_error: 'Invalid JSON in tasks',
        config_editing_disabled: 'Config Editing Disabled',
        config_editing_disabled_desc: 'Direct configuration editing via the UI is currently disabled for security reasons and to address known bugs. Please use the server\'s configuration file for any changes.',
        http_s_config: 'HTTP/S Configuration',
        save_changes: 'Save Changes',
        started: 'started',
        stopped_action: 'stopped',
        action_failed: 'Action failed',
        switch_accepted: 'Switch request for {path} to {source} accepted',
        switch_failed: 'Switch failed',
        task_restarted: 'Task restarted successfully',
        task_restart_failed: 'Failed to restart task',
        task_started: 'Task started successfully',
        task_start_failed: 'Failed to start task',
        task_deleted: 'Task deleted successfully',
        task_delete_failed: 'Failed to delete task',
        switch_stopped: 'Switch task for {path} stopped',
        switch_stop_failed: 'Failed to stop switch task',
        start: 'Start',
        stop: 'Stop',
        video_player: 'Video Player',
        failed_fetch_streams: 'Failed to fetch streams',
        stream_deleted: 'Stream /{path} deleted',
        failed_delete_stream: 'Failed to delete stream',
        stream_restarted: 'Stream /{path} restarted',
        failed_restart_stream: 'Failed to restart stream',
        stream_stopped: 'Stream /{path} stopped',
        failed_stop_stream: 'Failed to stop stream',
        tree_view: 'Tree View',
        streams_tree: 'Streams Tree',
        broadcasts: 'Broadcasts',
        orphans: 'Orphan Sessions',
        publisher: 'Publisher',
        subscribers: 'Subscribers',
        no_tree_data: 'No active streams or sessions',
        failed_fetch_tree: 'Failed to fetch streams tree',
        state: 'State',
        session_state_CONNECTING: 'Connecting',
        session_state_CONNECTED: 'Connected',
        session_state_STARTING: 'Starting',
        session_state_RUNNING: 'Running',
        session_state_STOPPING: 'Stopping',
        session_state_STOPPED: 'Stopped',
        session_state_RESTARTING: 'Restarting',
        broadcast_state_REGISTERING: 'Registering',
        broadcast_state_REGISTERED: 'Registered',
        broadcast_state_LIVE: 'Live',
        broadcast_state_SWITCHING: 'Switching',
        broadcast_state_OFFLINE: 'Offline',
        broadcast_state_STOPPING: 'Stopping',
        broadcast_state_STOPPED: 'Stopped',
        failed_fetch_tasks: 'Failed to fetch tasks',
        failed_fetch_config: 'Failed to fetch configuration',
        grouping: 'Grouping',
        none: 'None',
        prefix: 'Prefix',
        multiple: 'Multiple',
        view_clients: 'View Clients',
        stream_details: 'Stream Details',
        stream_secret: 'Stream Secret (Password)',
        search_streams: 'Search streams...',
        audio: 'Audio',
        video: 'Video',
        time: 'Time',
        clients: 'Clients',
        codec: 'Codec',
        freq: 'Frequency',
        chan: 'Channels',
        size: 'Size',
        fps: 'FPS',
        switchable: 'Switchable',
        stream_id: 'Stream ID',
        details: 'Details',
        based_on: 'based on',
        visible_widgets: 'Visible Widgets',
        connections: 'Connections',
        network: 'Network',
        cpu: 'CPU',
        mem: 'Memory',
        task_app: 'App',
        task_name: 'Name',
        task_pattern: 'Pattern',
        task_mode: 'Mode',
        task_edge: 'Edge',
        task_rescale: 'Rescale',
        task_rtsp_transport: 'RTSP Transport',
        task_append_name: 'Append Name',
        task_rtmp: 'RTMP',
        task_rtmp_app: 'RTMP App',
        task_mp4: 'MP4',
        task_mp4_flags: 'MP4 Flags',
        task_hls: 'HLS',
        task_hls_flags: 'HLS Flags',
        task_hls_keep: 'Keep HLS',
        task_dash: 'DASH',
        task_dash_flags: 'DASH Flags',
        task_dash_keep: 'Keep DASH',
        task_vc: 'Video Codec',
        task_vc_param: 'Video Codec Params',
        task_ac: 'Audio Codec',
        task_ac_param: 'Audio Codec Params',
        task_sources: 'Sources',
        task_default_source: 'Default Source',
        task_switch_timeout: 'Switch Timeout',
        task_slate_path: 'Slate Path',
        task_model: 'Output Models',
        model_vb: 'Video Bitrate',
        model_vf: 'Video Filter',
        model_vs: 'Video Size',
        model_ab: 'Audio Bitrate',
        no_tasks_configured: 'No tasks configured',
        task_n: 'Task',
        model_n: 'Model',
        task_input: 'Input',
        task_text_path: 'Text Path',
        stream_path: 'Stream Path',
    },
    de: {
        dashboard: 'Dashboard',
        streams: 'Streams',
        tasks: 'Aufgaben',
        profile: 'Profil',
        config: 'Konfiguration',
        refresh_stats: 'Statistiken aktualisieren',
        stats_refreshed: 'Statistiken erfolgreich aktualisiert',
        failed_refresh: 'Aktualisierung der Statistiken fehlgeschlagen',
        live: 'Live',
        viewers: 'Zuschauer',
        duration: 'Dauer',
        bitrate: 'Bitrate',
        start_time: 'Startzeit',
        arguments: 'Argumente',
        no_data: 'Keine Daten gefunden',
        snapshot: 'Schnappschuss machen',
        reload: 'Player neu laden',
        overview: 'Dashboard-Übersicht',
        server_info: 'Serverinformationen',
        active_streams: 'Aktive Streams',
        app: 'App',
        stream: 'Stream',
        stream_name: 'Stream-Name',
        publisher_id: 'Publisher-ID',
        publisher_state: 'Publisher-Status',
        broadcast_id: 'Broadcast-ID',
        broadcast_state: 'Broadcast-Status',
        actions: 'Aktionen',
        delete: 'Löschen',
        remove: 'Entfernen',
        add_task: 'Aufgabe hinzufügen',
        server_logs: 'Server-Logs',
        logs_connected: 'Verbunden',
        logs_connecting: 'Verbinde…',
        logs_disconnected: 'Getrennt',
        no_logs_yet: 'Noch keine Log-Nachrichten.',
        pause: 'Pausieren',
        resume: 'Fortsetzen',
        clear: 'Leeren',
        confirm_remove_task: 'Diese Aufgabe entfernen?',
        confirm_delete: 'Sind Sie sicher, dass Sie dies löschen möchten?',
        yes: 'Ja',
        no: 'Nein',
        component_switch: 'Switch',
        component_relay: 'Relay',
        component_trans: 'Trans',
        component_fission: 'Fission',
        component_rtmp: 'RTMP',
        component_av: 'A/V',
        background_tasks: 'Hintergrundaufgaben',
        service_controls: 'Dienststeuerung',
        running: 'LÄUFT',
        stopped: 'GESTOPPT',
        restart: 'Neustart',
        uptime: 'Laufzeit',
        url: 'URL',
        mode: 'Modus',
        path: 'Pfad',
        output_path: 'Ausgabepfad',
        status: 'Status',
        active_source: 'Aktive Quelle',
        pending: 'Ausstehend',
        switch_to: 'Umschalten auf',
        configured_sources: 'Konfigurierte Quellen',
        active_streams_select: 'Aktive Streams',
        save_config: 'Konfiguration speichern',
        config_updated: 'Konfiguration erfolgreich aktualisiert',
        config_failed: 'Aktualisierung fehlgeschlagen',
        http_config: 'HTTP-Konfiguration',
        https_config: 'HTTPS-Konfiguration',
        rtmp_config: 'RTMP-Konfiguration',
        auth_config: 'Authentifizierung',
        logging_config: 'Protokollierung',
        trans_config: 'Transcodierungs-Konfiguration',
        relay_config: 'Weiterleitungs-Konfiguration',
        fission_config: 'Fission-Konfiguration',
        switch_config: 'Umschalter-Konfiguration',
        port: 'Port',
        enable_api: 'API aktivieren',
        web_root: 'Web-Verzeichnis',
        media_root: 'Medien-Verzeichnis',
        allow_origin: 'Allow Origin',
        ssl_key_path: 'SSL-Schlüsselpfad',
        ssl_cert_path: 'SSL-Zertifikatspfad',
        ssl_passphrase: 'SSL-Passphrase',
        ssl_port: 'SSL-Port',
        chunk_size: 'Chunk-Größe',
        ping_interval: 'Ping-Intervall',
        ping_timeout: 'Ping-Timeout',
        gop_cache: 'GOP-Cache aktivieren',
        api_auth: 'API-Authentifizierung',
        api_user: 'API-Benutzer',
        api_pass: 'API-Passwort',
        play_auth: 'Wiedergabe-Authentifizierung',
        publish_auth: 'Veröffentlichungs-Authentifizierung',
        secret_key: 'Geheimschlüssel',
        log_type: 'Protokolltyp',
        log_length: 'Rolling-Log-Länge',
        ffmpeg_path: 'FFmpeg-Pfad',
        tasks_json: 'Aufgaben (JSON)',
        json_error: 'Ungültiges JSON in den Aufgaben',
        config_editing_disabled: 'Konfigurationsbearbeitung deaktiviert',
        config_editing_disabled_desc: 'Die direkte Bearbeitung der Konfiguration über die Benutzeroberfläche ist derzeit aus Sicherheitsgründen und zur Behebung bekannter Fehler deaktiviert. Bitte verwenden Sie die Konfigurationsdatei des Servers für alle Änderungen.',
        http_s_config: 'HTTP/S-Konfiguration',
        save_changes: 'Änderungen speichern',
        started: 'gestartet',
        stopped_action: 'gestoppt',
        action_failed: 'Aktion fehlgeschlagen',
        switch_accepted: 'Umschaltanfrage für {path} auf {source} akzeptiert',
        switch_failed: 'Umschalten fehlgeschlagen',
        task_restarted: 'Aufgabe erfolgreich neu gestartet',
        task_restart_failed: 'Fehler beim Neustart der Aufgabe',
        task_started: 'Aufgabe erfolgreich gestartet',
        task_start_failed: 'Fehler beim Starten der Aufgabe',
        switch_stopped: 'Switch-Aufgabe für {path} gestoppt',
        switch_stop_failed: 'Fehler beim Stoppen der Switch-Aufgabe',
        start: 'Start',
        stop: 'Stopp',
        stream_stopped: 'Stream /{path} gestoppt',
        failed_stop_stream: 'Fehler beim Stoppen des Streams',
        task_deleted: 'Aufgabe erfolgreich gelöscht',
        task_delete_failed: 'Aufgabe konnte nicht gelöscht werden',
        video_player: 'Video-Player',
        failed_fetch_streams: 'Fehler beim Abrufen der Streams',
        stream_deleted: 'Stream /{path} gelöscht',
        failed_delete_stream: 'Fehler beim Löschen des Streams',
        stream_restarted: 'Stream /{path} neu gestartet',
        failed_restart_stream: 'Fehler beim Neustart des Streams',
        tree_view: 'Baumansicht',
        streams_tree: 'Streams-Baum',
        broadcasts: 'Übertragungen',
        orphans: 'Verwaiste Sitzungen',
        publisher: 'Publisher',
        subscribers: 'Abonnenten',
        no_tree_data: 'Keine aktiven Streams oder Sitzungen',
        failed_fetch_tree: 'Fehler beim Abrufen des Stream-Baums',
        state: 'Status',
        session_state_CONNECTING: 'Verbindet',
        session_state_CONNECTED: 'Verbunden',
        session_state_STARTING: 'Startet',
        session_state_RUNNING: 'Aktiv',
        session_state_STOPPING: 'Stoppt',
        session_state_STOPPED: 'Gestoppt',
        session_state_RESTARTING: 'Neustart',
        broadcast_state_REGISTERING: 'Registriert sich',
        broadcast_state_REGISTERED: 'Registriert',
        broadcast_state_LIVE: 'Live',
        broadcast_state_SWITCHING: 'Umschaltend',
        broadcast_state_OFFLINE: 'Offline',
        broadcast_state_STOPPING: 'Stoppt',
        broadcast_state_STOPPED: 'Gestoppt',
        failed_fetch_tasks: 'Fehler beim Abrufen der Aufgaben',
        failed_fetch_config: 'Fehler beim Abrufen der Konfiguration',
        grouping: 'Gruppierung',
        none: 'Keine',
        prefix: 'Präfix',
        multiple: 'Mehrere',
        view_clients: 'Clients anzeigen',
        stream_details: 'Stream-Details',
        stream_secret: 'Stream-Geheimnis (Passwort)',
        search_streams: 'Streams suchen...',
        audio: 'Audio',
        video: 'Video',
        time: 'Zeit',
        clients: 'Clients',
        codec: 'Codec',
        freq: 'Frequenz',
        chan: 'Kanäle',
        size: 'Größe',
        fps: 'FPS',
        switchable: 'Umschaltbar',
        stream_id: 'Stream-ID',
        details: 'Details',
        based_on: 'basierend auf',
        visible_widgets: 'Sichtbare Widgets',
        connections: 'Verbindungen',
        network: 'Netzwerk',
        cpu: 'CPU',
        mem: 'Speicher',
        task_app: 'App',
        task_name: 'Name',
        task_pattern: 'Muster',
        task_mode: 'Modus',
        task_edge: 'Edge',
        task_rescale: 'Skalierung',
        task_rtsp_transport: 'RTSP-Transport',
        task_append_name: 'Name anhängen',
        task_rtmp: 'RTMP',
        task_rtmp_app: 'RTMP-App',
        task_mp4: 'MP4',
        task_mp4_flags: 'MP4-Flags',
        task_hls: 'HLS',
        task_hls_flags: 'HLS-Flags',
        task_hls_keep: 'HLS behalten',
        task_dash: 'DASH',
        task_dash_flags: 'DASH-Flags',
        task_dash_keep: 'DASH behalten',
        task_vc: 'Video-Codec',
        task_vc_param: 'Video-Codec-Parameter',
        task_ac: 'Audio-Codec',
        task_ac_param: 'Audio-Codec-Parameter',
        task_sources: 'Quellen',
        task_default_source: 'Standardquelle',
        task_switch_timeout: 'Umschalt-Timeout',
        task_slate_path: 'Slate-Pfad',
        task_model: 'Ausgabe-Modelle',
        model_vb: 'Video-Bitrate',
        model_vf: 'Video-Filter',
        model_vs: 'Video-Größe',
        model_ab: 'Audio-Bitrate',
        no_tasks_configured: 'Keine Aufgaben konfiguriert',
        task_n: 'Aufgabe',
        model_n: 'Modell',
        component_static: 'Static',
        task_input: 'Eingabe',
        task_text_path: 'Textpfad',
        stream_path: 'Stream-Pfad',
    }
};

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getInitialLocale = (): Locale => {
    const browserLang = navigator.language.split('-')[0];
    if (browserLang in translations) {
        return browserLang as Locale;
    }
    return 'en';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [locale, setLocale] = useLocalStorage<Locale>('nms.admin.locale', getInitialLocale());

    const t = useCallback((key: string) => {
        const translationSet = translations[locale] || translations['en'];
        return translationSet[key] || key;
    }, [locale]);

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useTranslation must be used within a LanguageProvider');
    }
    return context;
};
