import React, { createContext, useContext, ReactNode, useCallback } from 'react';
import { useLocalStorage } from 'usehooks-ts';

type Locale = 'en' | 'de';

interface Translations {
    [key: string]: string;
}

const translations: Record<Locale, Translations> = {
    en: {
        dashboard: 'Dashboard',
        streams: 'Streams',
        tasks: 'Tasks',
        profile: 'Profile',
        config: 'Configuration',
        refresh_stats: 'Refresh Stats',
        stats_refreshed: 'Stats refreshed successfully',
        failed_refresh: 'Failed to refresh stats',
        live: 'Live',
        viewers: 'Viewers',
        duration: 'Duration',
        bitrate: 'Bitrate',
        start_time: 'Start Time',
        arguments: 'Arguments',
        no_data: 'No data found',
        snapshot: 'Take Snapshot',
        reload: 'Reload Player',
        overview: 'Dashboard Overview',
        server_info: 'Server Information',
        active_streams: 'Active Streams',
        app: 'App',
        stream_name: 'Stream Name',
        actions: 'Actions',
        delete: 'Delete',
        confirm_delete: 'Are you sure you want to delete this?',
        yes: 'Yes',
        no: 'No',
        component_switch: 'Switch',
        component_relay: 'Relay',
        component_trans: 'Trans',
        component_fission: 'Fission',
        component_rtmp: 'RTMP',
        component_av: 'A/V',
        background_tasks: 'Background Tasks',
        service_controls: 'Service Controls',
        running: 'RUNNING',
        stopped: 'STOPPED',
        restart: 'Restart',
        uptime: 'Uptime',
        url: 'URL',
        mode: 'Mode',
        path: 'Path',
        output_path: 'Output Path',
        status: 'Status',
        active_source: 'Active Source',
        pending: 'Pending',
        switch_to: 'Switch To',
        configured_sources: 'Configured Sources',
        active_streams_select: 'Active Streams',
        save_config: 'Save Configuration',
        config_updated: 'Configuration updated successfully',
        config_failed: 'Update failed',
        http_config: 'HTTP Configuration',
        https_config: 'HTTPS Configuration',
        rtmp_config: 'RTMP Configuration',
        auth_config: 'Authentication',
        logging_config: 'Logging',
        trans_config: 'Trans Configuration',
        relay_config: 'Relay Configuration',
        fission_config: 'Fission Configuration',
        switch_config: 'Switch Configuration',
        port: 'Port',
        enable_api: 'Enable API',
        web_root: 'Web Root',
        media_root: 'Media Root',
        allow_origin: 'Allow Origin',
        ssl_key_path: 'SSL Key Path',
        ssl_cert_path: 'SSL Cert Path',
        ssl_passphrase: 'SSL Passphrase',
        ssl_port: 'SSL Port',
        chunk_size: 'Chunk Size',
        ping_interval: 'Ping Interval',
        ping_timeout: 'Ping Timeout',
        gop_cache: 'Enable GOP Cache',
        api_auth: 'API Auth',
        api_user: 'API User',
        api_pass: 'API Password',
        play_auth: 'Play Auth',
        publish_auth: 'Publish Auth',
        secret_key: 'Secret Key',
        log_type: 'Log Type',
        log_length: 'Rolling Log Length',
        ffmpeg_path: 'FFmpeg Path',
        tasks_json: 'Tasks (JSON)',
        json_error: 'Invalid JSON in tasks',
        config_editing_disabled: 'Config Editing Disabled',
        config_editing_disabled_desc: 'Direct configuration editing via the UI is currently disabled for security reasons and to address known bugs. Please use the server\'s configuration file for any changes.',
        http_s_config: 'HTTP/S Configuration',
        save_changes: 'Save Changes',
        started: 'started',
        stopped_action: 'stopped',
        action_failed: 'Action failed',
        switch_accepted: 'Switch request for {path} to {source} accepted',
        switch_failed: 'Switch failed',
        task_restarted: 'Task restarted successfully',
        task_restart_failed: 'Failed to restart task',
        task_deleted: 'Task deleted successfully',
        task_delete_failed: 'Failed to delete task',
        video_player: 'Video Player',
        failed_fetch_streams: 'Failed to fetch streams',
        stream_deleted: 'Stream /{path} deleted',
        failed_delete_stream: 'Failed to delete stream',
        tree_view: 'Tree View',
        streams_tree: 'Streams Tree',
        broadcasts: 'Broadcasts',
        orphans: 'Orphan Sessions',
        publisher: 'Publisher',
        subscribers: 'Subscribers',
        no_tree_data: 'No active streams or sessions',
        failed_fetch_tree: 'Failed to fetch streams tree',
        failed_fetch_tasks: 'Failed to fetch tasks',
        failed_fetch_config: 'Failed to fetch configuration',
        grouping: 'Grouping',
        none: 'None',
        prefix: 'Prefix',
        view_clients: 'View Clients',
        stream_details: 'Stream Details',
        stream_secret: 'Stream Secret (Password)',
        search_streams: 'Search streams...',
        audio: 'Audio',
        video: 'Video',
        time: 'Time',
        clients: 'Clients',
        codec: 'Codec',
        freq: 'Frequency',
        chan: 'Channels',
        size: 'Size',
        fps: 'FPS',
        switchable: 'Switchable',
        stream_id: 'Stream ID',
        details: 'Details',
        based_on: 'based on',
        visible_widgets: 'Visible Widgets',
        connections: 'Connections',
        network: 'Network',
        cpu: 'CPU',
        mem: 'Memory',
    },
    de: {
        dashboard: 'Dashboard',
        streams: 'Streams',
        tasks: 'Aufgaben',
        profile: 'Profil',
        config: 'Konfiguration',
        refresh_stats: 'Statistiken aktualisieren',
        stats_refreshed: 'Statistiken erfolgreich aktualisiert',
        failed_refresh: 'Aktualisierung der Statistiken fehlgeschlagen',
        live: 'Live',
        viewers: 'Zuschauer',
        duration: 'Dauer',
        bitrate: 'Bitrate',
        start_time: 'Startzeit',
        arguments: 'Argumente',
        no_data: 'Keine Daten gefunden',
        snapshot: 'Schnappschuss machen',
        reload: 'Player neu laden',
        overview: 'Dashboard-Übersicht',
        server_info: 'Serverinformationen',
        active_streams: 'Aktive Streams',
        app: 'App',
        stream_name: 'Stream-Name',
        actions: 'Aktionen',
        delete: 'Löschen',
        confirm_delete: 'Sind Sie sicher, dass Sie dies löschen möchten?',
        yes: 'Ja',
        no: 'Nein',
        component_switch: 'Switch',
        component_relay: 'Relay',
        component_trans: 'Trans',
        component_fission: 'Fission',
        component_rtmp: 'RTMP',
        component_av: 'A/V',
        background_tasks: 'Hintergrundaufgaben',
        service_controls: 'Dienststeuerung',
        running: 'LÄUFT',
        stopped: 'GESTOPPT',
        restart: 'Neustart',
        uptime: 'Laufzeit',
        url: 'URL',
        mode: 'Modus',
        path: 'Pfad',
        output_path: 'Ausgabepfad',
        status: 'Status',
        active_source: 'Aktive Quelle',
        pending: 'Ausstehend',
        switch_to: 'Umschalten auf',
        configured_sources: 'Konfigurierte Quellen',
        active_streams_select: 'Aktive Streams',
        save_config: 'Konfiguration speichern',
        config_updated: 'Konfiguration erfolgreich aktualisiert',
        config_failed: 'Aktualisierung fehlgeschlagen',
        http_config: 'HTTP-Konfiguration',
        https_config: 'HTTPS-Konfiguration',
        rtmp_config: 'RTMP-Konfiguration',
        auth_config: 'Authentifizierung',
        logging_config: 'Protokollierung',
        trans_config: 'Transcodierungs-Konfiguration',
        relay_config: 'Weiterleitungs-Konfiguration',
        fission_config: 'Fission-Konfiguration',
        switch_config: 'Umschalter-Konfiguration',
        port: 'Port',
        enable_api: 'API aktivieren',
        web_root: 'Web-Verzeichnis',
        media_root: 'Medien-Verzeichnis',
        allow_origin: 'Allow Origin',
        ssl_key_path: 'SSL-Schlüsselpfad',
        ssl_cert_path: 'SSL-Zertifikatspfad',
        ssl_passphrase: 'SSL-Passphrase',
        ssl_port: 'SSL-Port',
        chunk_size: 'Chunk-Größe',
        ping_interval: 'Ping-Intervall',
        ping_timeout: 'Ping-Timeout',
        gop_cache: 'GOP-Cache aktivieren',
        api_auth: 'API-Authentifizierung',
        api_user: 'API-Benutzer',
        api_pass: 'API-Passwort',
        play_auth: 'Wiedergabe-Authentifizierung',
        publish_auth: 'Veröffentlichungs-Authentifizierung',
        secret_key: 'Geheimschlüssel',
        log_type: 'Protokolltyp',
        log_length: 'Rolling-Log-Länge',
        ffmpeg_path: 'FFmpeg-Pfad',
        tasks_json: 'Aufgaben (JSON)',
        json_error: 'Ungültiges JSON in den Aufgaben',
        config_editing_disabled: 'Konfigurationsbearbeitung deaktiviert',
        config_editing_disabled_desc: 'Die direkte Bearbeitung der Konfiguration über die Benutzeroberfläche ist derzeit aus Sicherheitsgründen und zur Behebung bekannter Fehler deaktiviert. Bitte verwenden Sie die Konfigurationsdatei des Servers für alle Änderungen.',
        http_s_config: 'HTTP/S-Konfiguration',
        save_changes: 'Änderungen speichern',
        started: 'gestartet',
        stopped_action: 'gestoppt',
        action_failed: 'Aktion fehlgeschlagen',
        switch_accepted: 'Umschaltanfrage für {path} auf {source} akzeptiert',
        switch_failed: 'Umschalten fehlgeschlagen',
        task_restarted: 'Aufgabe erfolgreich neu gestartet',
        task_restart_failed: 'Aufgabe konnte nicht neu gestartet werden',
        task_deleted: 'Aufgabe erfolgreich gelöscht',
        task_delete_failed: 'Aufgabe konnte nicht gelöscht werden',
        video_player: 'Video-Player',
        failed_fetch_streams: 'Fehler beim Abrufen der Streams',
        stream_deleted: 'Stream /{path} gelöscht',
        failed_delete_stream: 'Fehler beim Löschen des Streams',
        tree_view: 'Baumansicht',
        streams_tree: 'Streams-Baum',
        broadcasts: 'Übertragungen',
        orphans: 'Verwaiste Sitzungen',
        publisher: 'Publisher',
        subscribers: 'Abonnenten',
        no_tree_data: 'Keine aktiven Streams oder Sitzungen',
        failed_fetch_tree: 'Fehler beim Abrufen des Stream-Baums',
        failed_fetch_tasks: 'Fehler beim Abrufen der Aufgaben',
        failed_fetch_config: 'Fehler beim Abrufen der Konfiguration',
        grouping: 'Gruppierung',
        none: 'Keine',
        prefix: 'Präfix',
        view_clients: 'Clients anzeigen',
        stream_details: 'Stream-Details',
        stream_secret: 'Stream-Geheimnis (Passwort)',
        search_streams: 'Streams suchen...',
        audio: 'Audio',
        video: 'Video',
        time: 'Zeit',
        clients: 'Clients',
        codec: 'Codec',
        freq: 'Frequenz',
        chan: 'Kanäle',
        size: 'Größe',
        fps: 'FPS',
        switchable: 'Umschaltbar',
        stream_id: 'Stream-ID',
        details: 'Details',
        based_on: 'basierend auf',
        visible_widgets: 'Sichtbare Widgets',
        connections: 'Verbindungen',
        network: 'Netzwerk',
        cpu: 'CPU',
        mem: 'Speicher',
    }
};

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getInitialLocale = (): Locale => {
    const browserLang = navigator.language.split('-')[0];
    if (browserLang in translations) {
        return browserLang as Locale;
    }
    return 'en';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [locale, setLocale] = useLocalStorage<Locale>('nms.admin.locale', getInitialLocale());

    const t = useCallback((key: string) => {
        const translationSet = translations[locale] || translations['en'];
        return translationSet[key] || key;
    }, [locale]);

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useTranslation must be used within a LanguageProvider');
    }
    return context;
};
